# Generated by Django 3.2 on 2021-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customer_added_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('description', models.TextField(max_length=300)),
                ('Added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
