# Generated by Django 3.2 on 2021-05-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210507_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='fare',
            field=models.FloatField(),
        ),
    ]
