# Generated by Django 3.2 on 2021-05-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_tour_fare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
