# Generated by Django 3.2 on 2021-05-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=40)),
                ('tour_image', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('place_from', models.CharField(max_length=30)),
                ('place_to', models.CharField(max_length=30)),
                ('places_to_be', models.TextField(max_length=500)),
                ('days', models.IntegerField()),
                ('night_days', models.IntegerField()),
                ('fare', models.FloatField()),
                ('tour_descriptions', models.TextField(max_length='1000')),
            ],
        ),
    ]
