# Generated by Django 3.2 on 2021-05-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='night_days',
            new_name='nights',
        ),
    ]
