# Generated by Django 3.2 on 2021-05-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Payment_Method',
            field=models.CharField(default='online', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Payment_status',
            field=models.BooleanField(default=True),
        ),
    ]
