# Generated by Django 3.2 on 2021-05-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210517_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='To_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
    ]
