# Generated by Django 3.2 on 2021-05-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20210518_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
